spring:
  application:
    name: hyeonjoon_blog
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_LOCAL_HOST}/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}

  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: ${REDIS_LOCAL_HOST}
      port: ${REDIS_LOCAL_PORT}
      connect-timeout: 6

file:
  path: src/main/resources/uploads

server:
  servlet:
    context-path: /api